# Generated by Django 3.1 on 2020-08-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='descricao',
            field=models.TextField(),
        ),
    ]
